#############################################
## Ubuntu
#############################################

- name: データベースとユーザーの作成
  become: yes
  become_method: sudo
  import_tasks:
    file: create_debian.yml
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_major_version == "22"

#############################################
## Amazon Linux
#############################################

- name: データベースとユーザーの作成
  become: yes
  become_method: sudo
  import_tasks:
    file: create_amazon.yml
  when:
    - ansible_distribution in ["Amazon"]
    - ansible_distribution_major_version == "2023"