#############################################
## Ubuntu
#############################################

- name: 変数の読み込み
  import_tasks:
    file: create_debian.yml
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_major_version == "22"

#############################################
## Amazon Linux
#############################################

- name: 変数の読み込み
  import_tasks:
    file: create_amazon.yml
  when:
    - ansible_distribution in ["Amazon"]
    - ansible_distribution_major_version == "2023"