#############################################
## Ubuntu
#############################################

- name: 変数の読み込み (Ubuntu 22.04 LTS)
  include_vars:
    file: "debian_vars.yml"
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_major_version == "22"

#############################################
## Amazon Linux
#############################################

- name: 変数の読み込み (Amazon Linux 2023)
  include_vars:
    file: "amazon_vars.yml"
  when:
    - ansible_distribution in ["Amazon"]
    - ansible_distribution_major_version == "2023"