- name: MariaDBと必要なパッケージのインストール (Amazon Linux 2023)
  dnf:
    name: "{{ mariadb_packages }}"
    state: present
  when:
    - ansible_distribution_major_version == "2023"

- name: Pythonパッケージのインストール (Amazon Linux 2023)
  pip: 
    name: "{{ python_packages }}"