#############################################
## Ubuntu
#############################################

- name: MariaDBと必要なパッケージのインストール
  import_tasks:
    file: "install_debian.yml"
  when:
    - ansible_distribution in ["Ubuntu"]

#############################################
## Amazon Linux
#############################################

- name: MariaDBと必要なパッケージのインストール
  import_tasks:
    file: "install_amazon.yml"
  when:
    - ansible_distribution in ["Amazon"]