- name: 変数の読み込み
  import_tasks:
    file: "import_vars.yml"

- name: パッケージのインストール
  import_tasks:
    file: "install_packages.yml"

- name: MariaDBの有効化
  service:
    name: mariadb
    enabled: yes
    daemon_reload: yes
    state: started

- name: データベース・データベースユーザーを作成
  import_tasks:
    file: create.yml

- name: MariaDBを有効化し起動
  systemd:
    name: mariadb
    enabled: yes
    daemon_reload: yes
    state: started
