#############################################
## Ubuntu
#############################################

- name: Apacheを有効化し起動
  import_tasks:
    file: "start_debian.yml"
  when:
    - ansible_distribution in ["Ubuntu"]

#############################################
## Amazon
#############################################

- name: Apacheを有効化し起動
  import_tasks:
    file: "start_amazon.yml"
  when:
    - ansible_distribution in ["Amazon"]