#############################################
## Ubuntu
#############################################

- name: WordPressフォルダーのコピー
  become: yes
  become_method: sudo
  import_tasks:
    file: "copy_debian.yml"
  when:
    - ansible_distribution in ["Ubuntu"]

#############################################
## Amazon Linux
#############################################

- name: WordPressフォルダーのコピー
  become: yes
  become_method: sudo
  import_tasks:
    file: "copy_amazon.yml"
  when:
    - ansible_distribution in ["Amazon"]