#############################################
## Ubuntu
#############################################

- name: httpd.confの編集
  become: yes
  become_method: sudo
  import_tasks:
    file: "edit_debian.yml"
  when:
    - ansible_distribution in ["Ubuntu"]

#############################################
## Amazon Linux
#############################################

- name: httpd.confの編集
  become: yes
  become_method: sudo
  import_tasks:
    file: "edit_amazon.yml"
  when:
    - ansible_distribution in ["Amazon"]