#############################################
## Ubuntu
#############################################

- name: Apacheを再起動
  service:
    name: apache2
    state: restarted
  when:
    - ansible_distribution in ["Ubuntu"]
    - ansible_distribution_major_version == "22"

#############################################
## Amazon Linux
#############################################

- name: Apacheを再起動
  service:
    name: httpd
    state: restarted
  when:
    - ansible_distribution in ["Amazon"]
    - ansible_distribution_major_version == "2023"