name: "AWS Deploy"

on:
  pull_request: 
    branches: 
      - main
    types: closed

env:
  AWS_REGION : "ap-northeast-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/prod"

    outputs:
      ec2_dns: ${{ steps.output.outputs.public_dns }}
      ec2_ip: ${{ steps.output.outputs.public_ip }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
          .terraform_wrapper: true

      - name: Terraform format
        id: fmt
        run: terraform fmt -recursive -check -diff
        continue-on-error: true

      - name: Terraform init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TFSTATE_BUCKET }}" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION  }}" \
            -backend-config="encrypt=true"

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: output
        run: |
          echo "public_dns=$(terraform output -raw ec2_public_dns)" >> $GITHUB_OUTPUT
          echo "public_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

  ansible:
    needs: deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./ansible"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: インベントリファイルの作成
        run:  |
          echo "[amazon]" > inventories/prod/inventory.ini
          echo "amazon ansible_host=${{ needs.deploy.outputs.ec2_dns }}" >> inventories/prod/inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3.9" >> inventories/prod/inventory.ini

      - name: SSHキーの作成
        run: |
          sudo apt-get install -y rsync
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/key.pem
          chmod 400 /tmp/key.pem

      - name: ansibleのインストール
        run: |
          sudo apt install -y ansible

      - name: ansibleの実行
        run: ansible-playbook -i inventories/prod/inventory.ini site.yml --private-key /tmp/key.pem -u ${{ secrets.REMOTE_USER }}